# NumPy: From Basics to Advanced

**Purpose:** Build the NumPy foundation you need to read and understand pandas code in ML/AI projects.

NumPy is the bedrock beneath pandas, scikit-learn, TensorFlow, and PyTorch. Every `DataFrame` column is ultimately a NumPy array. Understanding NumPy means you can read pandas and ML code fluently.

**How this notebook is organized:**
1. Creating Arrays
2. Array Properties (shape, dtype, ndim)
3. Indexing and Slicing
4. Boolean Indexing (heavily used in pandas filtering)
5. Reshaping and Transposing
6. Math and Aggregation
7. Broadcasting (the "magic" behind pandas operations)
8. Random Number Generation (used everywhere in ML)
9. Linear Algebra Basics
10. Real Patterns You'll See in ML/AI Code

In [1]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.5


## 1. Creating Arrays

The `ndarray` (N-dimensional array) is NumPy's core object. Every pandas Series and DataFrame column is backed by one.

In [2]:
# From a Python list — simplest way
a = np.array([1, 2, 3, 4, 5])
print("From list:", a)

# 2D array (matrix) — from nested lists
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\n2D array:\n", matrix)

# Specifying the data type explicitly
floats = np.array([1, 2, 3], dtype='float32')
print("\nFloat32 array:", floats)

From list: [1 2 3 4 5]

2D array:
 [[1 2 3]
 [4 5 6]]

Float32 array: [1. 2. 3.]


In [3]:
# Common factory functions — you'll see these constantly in ML code

# Zeros and ones (e.g., initializing weight matrices, creating masks)
zeros = np.zeros((3, 4))        # 3 rows, 4 cols of 0.0
ones = np.ones((2, 3))          # 2 rows, 3 cols of 1.0
print("Zeros (3x4):\n", zeros)
print("\nOnes (2x3):\n", ones)

# Full — fill with a specific value
fives = np.full((2, 2), 5)
print("\nFull (2x2, value=5):\n", fives)

# Identity matrix (used in linear algebra, regularization)
eye = np.eye(3)
print("\nIdentity 3x3:\n", eye)

Zeros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]

Full (2x2, value=5):
 [[5 5]
 [5 5]]

Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Ranges and sequences

# arange — like Python's range() but returns an array
a = np.arange(0, 10, 2)  # start, stop, step
print("arange(0,10,2):", a)

# linspace — evenly spaced numbers over an interval (great for plotting)
b = np.linspace(0, 1, 5)  # 5 points from 0 to 1 inclusive
print("linspace(0,1,5):", b)

# logspace — log-scaled spacing (used for hyperparameter search grids)
c = np.logspace(-3, 3, 7)  # 10^-3 to 10^3
print("logspace(-3,3,7):", c)

arange(0,10,2): [0 2 4 6 8]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]
logspace(-3,3,7): [1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


## 2. Array Properties — shape, dtype, ndim

These three properties appear constantly when debugging ML pipelines. Shape mismatches are the #1 source of errors.

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("shape:", arr.shape)     # (2, 3) — 2 rows, 3 columns
print("ndim:", arr.ndim)       # 2 — number of dimensions (axes)
print("dtype:", arr.dtype)     # int64 (or int32 on Windows)
print("size:", arr.size)       # 6 — total number of elements
print("itemsize:", arr.itemsize, "bytes")  # bytes per element
print("nbytes:", arr.nbytes, "bytes")      # total memory used

shape: (2, 3)
ndim: 2
dtype: int64
size: 6
itemsize: 8 bytes
nbytes: 48 bytes


In [6]:
# Common dtypes you'll encounter in ML code
# int32, int64    — integer labels, counts, indices
# float32, float64 — features, weights, predictions
# bool            — masks, filters
# object          — strings in pandas (not a true NumPy type)

# Converting dtypes — you'll see .astype() in nearly every ML pipeline
a = np.array([1.7, 2.3, 3.9])
print("Original (float64):", a, a.dtype)

a_int = a.astype('int32')     # Truncates, does NOT round
print("As int32:          ", a_int, a_int.dtype)

a_bool = np.array([0, 1, 0, 1]).astype(bool)
print("As bool:           ", a_bool, a_bool.dtype)

Original (float64): [1.7 2.3 3.9] float64
As int32:           [1 2 3] int32
As bool:            [False  True False  True] bool


## 3. Indexing and Slicing

Identical syntax to Python lists but extended to multiple dimensions. Pandas `.iloc` uses the exact same logic.

In [7]:
# 1D indexing — same as Python lists
a = np.array([10, 20, 30, 40, 50])
print("Element at index 0:", a[0])      # 10
print("Last element:      ", a[-1])     # 50
print("Slice [1:4]:       ", a[1:4])    # [20, 30, 40]
print("Every other:       ", a[::2])    # [10, 30, 50]
print("Reversed:          ", a[::-1])   # [50, 40, 30, 20, 10]

Element at index 0: 10
Last element:       50
Slice [1:4]:        [20 30 40]
Every other:        [10 30 50]
Reversed:           [50 40 30 20 10]


In [8]:
# 2D indexing — arr[row, col]
m = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

print("Element [1,2]:", m[1, 2])          # 7  (row 1, col 2)
print("Entire row 0: ", m[0])             # [1, 2, 3, 4]
print("Entire col 1: ", m[:, 1])          # [2, 6, 10]
print("Submatrix:    \n", m[0:2, 1:3])    # rows 0-1, cols 1-2
print("Last row:     ", m[-1])            # [9, 10, 11, 12]

# The colon (:) means "all elements along this axis"
# You'll see this pattern everywhere: X[:, 0] means "all rows, column 0"

Element [1,2]: 7
Entire row 0:  [1 2 3 4]
Entire col 1:  [ 2  6 10]
Submatrix:    
 [[2 3]
 [6 7]]
Last row:      [ 9 10 11 12]


In [9]:
# Fancy indexing — selecting specific rows/cols by index arrays
# Used in ML for selecting specific samples or features

m = np.array([[1,  2,  3],
              [4,  5,  6],
              [7,  8,  9],
              [10, 11, 12]])

# Select rows 0 and 3
print("Rows [0,3]:\n", m[[0, 3]])

# Select specific elements: m[0,1], m[2,0], m[3,2]
print("Specific elements:", m[[0, 2, 3], [1, 0, 2]])  # [2, 7, 12]

Rows [0,3]:
 [[ 1  2  3]
 [10 11 12]]
Specific elements: [ 2  7 12]


## 4. Boolean Indexing (Masking)

**This is the single most important NumPy concept for reading pandas code.** When you see `df[df['age'] > 30]` in pandas, it's using NumPy boolean indexing under the hood.

In [10]:
ages = np.array([25, 32, 18, 47, 55, 29, 41])

# Step 1: Comparison creates a boolean array (the "mask")
mask = ages > 30
print("Mask (ages > 30):", mask)   # [False  True False  True  True False  True]

# Step 2: Use the mask to filter — only True positions are kept
print("Filtered:        ", ages[mask])  # [32, 47, 55, 41]

# Usually written in one line (exactly like pandas):
print("One-liner:       ", ages[ages > 30])

Mask (ages > 30): [False  True False  True  True False  True]
Filtered:         [32 47 55 41]
One-liner:        [32 47 55 41]


In [11]:
# Combining conditions — use & (and), | (or), ~ (not)
# IMPORTANT: Must use parentheses around each condition!
# This is the SAME syntax pandas uses: df[(cond1) & (cond2)]

ages = np.array([25, 32, 18, 47, 55, 29, 41])

# AND: ages between 25 and 45
result = ages[(ages >= 25) & (ages <= 45)]
print("25 <= age <= 45:", result)

# OR: ages under 20 or over 50
result = ages[(ages < 20) | (ages > 50)]
print("age<20 or age>50:", result)

# NOT: ages NOT over 30
result = ages[~(ages > 30)]
print("NOT age > 30:   ", result)

25 <= age <= 45: [25 32 29 41]
age<20 or age>50: [18 55]
NOT age > 30:    [25 18 29]


In [12]:
# np.where — conditional selection (like Excel IF or SQL CASE WHEN)
# Pattern: np.where(condition, value_if_true, value_if_false)

ages = np.array([25, 32, 18, 47, 55, 29, 41])
labels = np.where(ages >= 30, 'senior', 'junior')
print("Labels:", labels)

# np.where with just condition — returns indices where True
indices = np.where(ages > 40)
print("Indices where age>40:", indices[0])  # [3, 4, 6]
print("Values at those indices:", ages[indices])

Labels: ['junior' 'senior' 'junior' 'senior' 'senior' 'junior' 'senior']
Indices where age>40: [3 4 6]
Values at those indices: [47 55 41]


## 5. Reshaping and Transposing

ML models are very particular about input shapes. You'll constantly see `.reshape()`, `.T`, and `-1` in ML code.

In [13]:
# reshape — change dimensions without changing data
a = np.arange(12)
print("Original (12,):", a)

# Reshape to 3 rows x 4 cols
b = a.reshape(3, 4)
print("\nReshaped (3,4):\n", b)

# -1 means "figure out this dimension automatically"
# This is VERY common in ML code
c = a.reshape(-1, 3)    # "whatever rows needed" x 3 cols = (4, 3)
print("\nreshape(-1, 3) gives shape:", c.shape)

d = a.reshape(2, -1)    # 2 rows x "whatever cols needed" = (2, 6)
print("reshape(2, -1) gives shape:", d.shape)

Original (12,): [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(-1, 3) gives shape: (4, 3)
reshape(2, -1) gives shape: (2, 6)


In [14]:
# reshape(-1, 1) — convert 1D to column vector
# You'll see this ALL THE TIME in scikit-learn:
#   X = feature_array.reshape(-1, 1)  # sklearn expects 2D input
a = np.array([1, 2, 3, 4])
print("1D shape:    ", a.shape)          # (4,)
print("Column shape:", a.reshape(-1, 1).shape)  # (4, 1)
print("Row shape:   ", a.reshape(1, -1).shape)  # (1, 4)

# .flatten() and .ravel() — back to 1D
m = np.array([[1, 2], [3, 4]])
print("\nFlatten:", m.flatten())   # [1, 2, 3, 4]
print("Ravel:  ", m.ravel())      # Same result, but returns a view (more efficient)

1D shape:     (4,)
Column shape: (4, 1)
Row shape:    (1, 4)

Flatten: [1 2 3 4]
Ravel:   [1 2 3 4]


In [15]:
# Transpose — swap rows and columns
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Original (2,3):\n", m)
print("\nTransposed (3,2):\n", m.T)

# np.newaxis / None — add a dimension (same as reshape but more readable)
a = np.array([1, 2, 3])              # shape (3,)
print("\nnp.newaxis examples:")
print("Column:", a[:, np.newaxis].shape)  # (3, 1)
print("Row:   ", a[np.newaxis, :].shape)  # (1, 3)

# Stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nvstack:\n", np.vstack([a, b]))   # Stack vertically (row-wise)
print("hstack:", np.hstack([a, b]))        # Stack horizontally
print("column_stack:\n", np.column_stack([a, b]))  # Side by side as columns

Original (2,3):
 [[1 2 3]
 [4 5 6]]

Transposed (3,2):
 [[1 4]
 [2 5]
 [3 6]]

np.newaxis examples:
Column: (3, 1)
Row:    (1, 3)

vstack:
 [[1 2 3]
 [4 5 6]]
hstack: [1 2 3 4 5 6]
column_stack:
 [[1 4]
 [2 5]
 [3 6]]


## 6. Math and Aggregation

NumPy operations are **element-wise** by default. This is why `df['A'] + df['B']` works in pandas — it adds element by element.

In [16]:
# Element-wise arithmetic — no loops needed!
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b:  ", a + b)       # [11, 22, 33, 44]
print("a * b:  ", a * b)       # [10, 40, 90, 160]  (NOT matrix multiply!)
print("a / b:  ", a / b)       # [0.1, 0.1, 0.1, 0.1]
print("a ** 2: ", a ** 2)      # [1, 4, 9, 16]
print("a + 10: ", a + 10)      # [11, 12, 13, 14]  (scalar broadcast)

# These are the same operations pandas uses when you write:
# df['total'] = df['price'] * df['quantity']

a + b:   [11 22 33 44]
a * b:   [ 10  40  90 160]
a / b:   [0.1 0.1 0.1 0.1]
a ** 2:  [ 1  4  9 16]
a + 10:  [11 12 13 14]


In [17]:
# Aggregation functions — these power pandas .mean(), .sum(), .std(), etc.
data = np.array([10, 25, 33, 47, 55, 12, 89])

print("sum:   ", np.sum(data))        # or data.sum()
print("mean:  ", np.mean(data))       # or data.mean()
print("std:   ", np.std(data))        # standard deviation
print("min:   ", np.min(data))
print("max:   ", np.max(data))
print("argmin:", np.argmin(data))     # INDEX of minimum value
print("argmax:", np.argmax(data))     # INDEX of maximum value
print("median:", np.median(data))
print("cumsum:", np.cumsum(data))     # cumulative sum (used in finance)

sum:    271
mean:   38.714285714285715
std:    25.694436783721358
min:    10
max:    89
argmin: 0
argmax: 6
median: 33.0
cumsum: [ 10  35  68 115 170 182 271]


In [18]:
# axis parameter — aggregate along rows or columns
# axis=0: collapse rows (operate DOWN each column) — pandas default for .mean()
# axis=1: collapse columns (operate ACROSS each row)

m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Matrix:\n", m)
print("\nsum axis=0 (down cols): ", m.sum(axis=0))   # [12, 15, 18]
print("sum axis=1 (across rows):", m.sum(axis=1))    # [6, 15, 24]
print("mean axis=0:", m.mean(axis=0))                # [4., 5., 6.]

# In pandas: df.mean() uses axis=0 by default (mean of each column)
# In pandas: df.mean(axis=1) gives mean across columns for each row

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

sum axis=0 (down cols):  [12 15 18]
sum axis=1 (across rows): [ 6 15 24]
mean axis=0: [4. 5. 6.]


In [19]:
# Universal functions (ufuncs) — element-wise math
# These are used behind the scenes in many ML operations

a = np.array([1, 4, 9, 16])

print("sqrt:  ", np.sqrt(a))         # [1, 2, 3, 4]
print("exp:   ", np.exp([0, 1, 2]))  # e^x — used in softmax, logistic regression
print("log:   ", np.log([1, np.e, np.e**2]))  # natural log — used in log loss
print("log10: ", np.log10([1, 10, 100]))

# Clip — bound values to a range (used to prevent overflow/underflow)
a = np.array([-2, 0.5, 3, 1e10])
print("clip:  ", np.clip(a, 0, 1))   # [0, 0.5, 1, 1]

# abs
print("abs:   ", np.abs([-3, -1, 0, 2]))  # [3, 1, 0, 2]

sqrt:   [1. 2. 3. 4.]
exp:    [1.         2.71828183 7.3890561 ]
log:    [0. 1. 2.]
log10:  [0. 1. 2.]
clip:   [0.  0.5 1.  1. ]
abs:    [3 1 0 2]


## 7. Broadcasting

Broadcasting is how NumPy (and pandas) makes operations work between arrays of *different* shapes. It's the reason you can write `df['col'] - df['col'].mean()` and it just works.

In [20]:
# Rule: NumPy stretches the smaller array to match the larger one
# (without actually copying data — it's efficient)

# Scalar broadcast — add 10 to every element
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print("a + 10:\n", a + 10)

# 1D broadcast across rows — subtract column means
# This is EXACTLY what pandas does for: df - df.mean()
col_means = a.mean(axis=0)   # [2.5, 3.5, 4.5]
print("\nColumn means:", col_means)
print("Centered (a - means):\n", a - col_means)

a + 10:
 [[11 12 13]
 [14 15 16]]

Column means: [2.5 3.5 4.5]
Centered (a - means):
 [[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


In [21]:
# Broadcasting rules visualized:
#
# Shape (3, 4) + Shape (4,)   → works! (4,) is broadcast across all 3 rows
# Shape (3, 4) + Shape (3, 1) → works! (3,1) is broadcast across all 4 cols
# Shape (3, 4) + Shape (3,)   → ERROR! Trailing dimensions must match
#
# The rule: dimensions are compared from the RIGHT. Each must be equal, or one must be 1.

# Column broadcast — normalize each row by its own sum
m = np.array([[1, 2, 3],
              [4, 5, 6]])

row_sums = m.sum(axis=1, keepdims=True)  # shape (2, 1) — keepdims is key!
print("Row sums (keepdims):\n", row_sums)
print("\nNormalized rows:\n", m / row_sums)

# keepdims=True preserves the dimension so broadcasting works correctly
# Without it, row_sums would be shape (2,) which can't broadcast against (2,3)

Row sums (keepdims):
 [[ 6]
 [15]]

Normalized rows:
 [[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]]


## 8. NaN Handling

`np.nan` is how pandas represents missing values. Understanding NaN behavior prevents subtle bugs.

In [22]:
# NaN poisons everything it touches
a = np.array([1.0, 2.0, np.nan, 4.0, 5.0])

print("sum:     ", np.sum(a))      # nan! One NaN ruins the whole sum
print("mean:    ", np.mean(a))     # nan!

# Use nan-safe versions (pandas uses these internally)
print("\nnansum:  ", np.nansum(a))    # 12.0 — ignores NaN
print("nanmean: ", np.nanmean(a))    # 3.0
print("nanstd:  ", np.nanstd(a))
print("nanmax:  ", np.nanmax(a))

# Detecting NaN
print("\nisnan:   ", np.isnan(a))            # [False, False, True, False, False]
print("any NaN? ", np.any(np.isnan(a)))      # True
print("count NaN:", np.sum(np.isnan(a)))     # 1

# NaN comparisons are always False (even NaN == NaN is False!)
print("\nnan == nan:", np.nan == np.nan)      # False — this is by design

sum:      nan
mean:     nan

nansum:   12.0
nanmean:  3.0
nanstd:   1.5811388300841898
nanmax:   5.0

isnan:    [False False  True False False]
any NaN?  True
count NaN: 1

nan == nan: False


## 9. Random Number Generation

Used everywhere in ML: train/test splits, weight initialization, data augmentation, sampling, simulations.

In [23]:
# Modern API (NumPy >= 1.17): use np.random.default_rng()
rng = np.random.default_rng(seed=42)  # seed for reproducibility

# Uniform [0, 1)
print("uniform:     ", rng.random(5))

# Normal distribution (mean=0, std=1) — weight initialization
print("normal:      ", rng.standard_normal(5))

# Integers — random indices, labels
print("integers:    ", rng.integers(0, 10, size=5))

# Choice — random sampling (used in bootstrap, data augmentation)
items = ['cat', 'dog', 'bird', 'fish']
print("choice:      ", rng.choice(items, size=3, replace=False))

# Shuffle (in-place)
arr = np.arange(10)
rng.shuffle(arr)
print("shuffled:    ", arr)

# Permutation — shuffled copy (does NOT modify original)
print("permutation: ", rng.permutation(10))

uniform:      [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
normal:       [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
integers:     [5 3 1 9 7]
choice:       ['fish' 'dog' 'bird']
shuffled:     [6 9 1 5 4 0 8 7 3 2]
permutation:  [3 2 6 5 1 4 8 0 7 9]


In [24]:
# Legacy API — you'll still see this in older ML code and tutorials
# np.random.seed(42)           — global seed (less safe than rng)
# np.random.rand(3, 4)         — uniform 3x4
# np.random.randn(3, 4)        — normal 3x4
# np.random.randint(0, 10, 5)  — random ints
# np.random.choice(arr, 3)     — random pick
# np.random.shuffle(arr)       — in-place shuffle

# The legacy API works fine but the new rng API is preferred because:
# 1. No global state — each rng is independent
# 2. Better statistical properties
# 3. Thread-safe

np.random.seed(42)
print("Legacy rand:    ", np.random.rand(3))
print("Legacy randn:   ", np.random.randn(3))
print("Legacy randint: ", np.random.randint(0, 10, 5))

Legacy rand:     [0.37454012 0.95071431 0.73199394]
Legacy randn:    [-1.11188012  0.31890218  0.27904129]
Legacy randint:  [7 2 5 4 1]


## 10. Sorting and Searching

In [25]:
a = np.array([30, 10, 50, 20, 40])

# Sort — returns a sorted copy
print("sorted:  ", np.sort(a))

# Argsort — returns INDICES that would sort the array
# Heavily used in ML for ranking predictions, top-k results
order = np.argsort(a)
print("argsort: ", order)           # [1, 3, 0, 4, 2] — indices
print("verify:  ", a[order])        # [10, 20, 30, 40, 50]

# Top-3 smallest / largest
print("3 smallest indices:", np.argsort(a)[:3])
print("3 largest indices: ", np.argsort(a)[-3:])

# Unique values and counts — like pandas value_counts()
labels = np.array([0, 1, 1, 0, 2, 1, 0, 2])
vals, counts = np.unique(labels, return_counts=True)
print("\nunique values:", vals)
print("counts:       ", counts)

sorted:   [10 20 30 40 50]
argsort:  [1 3 0 4 2]
verify:   [10 20 30 40 50]
3 smallest indices: [1 3 0]
3 largest indices:  [0 4 2]

unique values: [0 1 2]
counts:        [3 3 2]


## 11. Linear Algebra Basics

Dot products, matrix multiplication, and norms appear in nearly every ML algorithm (regression, neural networks, PCA, etc.).

In [26]:
# Dot product — core of linear regression: y = X @ w
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("dot product:", np.dot(a, b))     # 1*4 + 2*5 + 3*6 = 32
print("same as @:  ", a @ b)            # @ operator (Python 3.5+)

# Matrix multiplication
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("\nA * B (element-wise):\n", A * B)     # NOT matrix multiply!
print("\nA @ B (matrix multiply):\n", A @ B)  # True matrix multiply
# A @ B is equivalent to np.matmul(A, B) and np.dot(A, B) for 2D

dot product: 32
same as @:   32

A * B (element-wise):
 [[ 5 12]
 [21 32]]

A @ B (matrix multiply):
 [[19 22]
 [43 50]]


In [27]:
# np.linalg — linear algebra module

A = np.array([[1, 2],
              [3, 4]])

# Inverse
print("Inverse:\n", np.linalg.inv(A))

# Determinant
print("\nDeterminant:", np.linalg.det(A))

# Norms — measure "size" of vectors/matrices
v = np.array([3, 4])
print("\nL2 norm (Euclidean):", np.linalg.norm(v))      # sqrt(9+16) = 5
print("L1 norm (Manhattan):", np.linalg.norm(v, ord=1)) # |3|+|4| = 7

# Eigenvalues — used in PCA, spectral clustering
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:", eigenvalues)

# Solving linear systems: Ax = b
b = np.array([5, 11])
x = np.linalg.solve(A, b)
print("\nSolve Ax=b, x:", x)
print("Verify A@x:   ", A @ x)  # Should equal b

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant: -2.0000000000000004

L2 norm (Euclidean): 5.0
L1 norm (Manhattan): 7.0

Eigenvalues: [-0.37228132  5.37228132]

Solve Ax=b, x: [1. 2.]
Verify A@x:    [ 5. 11.]


## 12. Views vs Copies — A Common Source of Bugs

NumPy slices return **views** (shared memory), not copies. This matters when you modify data.

In [28]:
# VIEW: slice shares memory with original — modifying one affects the other
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]
view[0] = 99
print("Original after modifying view:", original)  # [1, 99, 3, 4, 5] — changed!

# COPY: independent data — modifying one does NOT affect the other
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()
copy[0] = 99
print("Original after modifying copy:", original)  # [1, 2, 3, 4, 5] — unchanged

# Rule of thumb:
# - Basic slicing (a[1:4]) → view
# - Fancy indexing (a[[1,2,3]]) → copy
# - Boolean indexing (a[a > 3]) → copy
# - .copy() → always a copy
#
# Pandas warns about this with SettingWithCopyWarning

Original after modifying view: [ 1 99  3  4  5]
Original after modifying copy: [1 2 3 4 5]


## 13. Real Patterns You'll See in ML/AI Code

These are actual NumPy patterns from real ML projects — the payoff for everything above.

In [29]:
# Pattern 1: Standardization (z-score normalization)
# You'll see this in almost every ML pipeline
# Formula: (x - mean) / std

data = np.array([150, 160, 170, 180, 190], dtype='float64')
standardized = (data - data.mean()) / data.std()
print("Standardized:", standardized)
print("Mean ≈ 0:    ", standardized.mean())
print("Std ≈ 1:     ", standardized.std())

Standardized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Mean ≈ 0:     0.0
Std ≈ 1:      0.9999999999999999


In [30]:
# Pattern 2: Min-Max normalization (scale to [0, 1])
data = np.array([150, 160, 170, 180, 190], dtype='float64')
normalized = (data - data.min()) / (data.max() - data.min())
print("Normalized to [0,1]:", normalized)

Normalized to [0,1]: [0.   0.25 0.5  0.75 1.  ]


In [31]:
# Pattern 3: Softmax — converts raw scores to probabilities (neural networks)
def softmax(x):
    e_x = np.exp(x - np.max(x))  # subtract max for numerical stability
    return e_x / e_x.sum()

logits = np.array([2.0, 1.0, 0.1])
probs = softmax(logits)
print("Logits:       ", logits)
print("Probabilities:", probs)
print("Sum = 1?      ", probs.sum())

Logits:        [2.  1.  0.1]
Probabilities: [0.65900114 0.24243297 0.09856589]
Sum = 1?       1.0


In [32]:
# Pattern 4: Sigmoid — logistic regression, binary classification
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([-5, -1, 0, 1, 5])
print("Sigmoid:", sigmoid(x))
# Output is always between 0 and 1 — interprets as probability

Sigmoid: [0.00669285 0.26894142 0.5        0.73105858 0.99330715]


In [33]:
# Pattern 5: One-hot encoding (manual) — used in neural networks
labels = np.array([0, 2, 1, 0, 3])  # 4 classes
n_classes = labels.max() + 1
one_hot = np.zeros((len(labels), n_classes))
one_hot[np.arange(len(labels)), labels] = 1  # fancy indexing trick

print("Labels:", labels)
print("One-hot:\n", one_hot)

Labels: [0 2 1 0 3]
One-hot:
 [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [34]:
# Pattern 6: Train/test split (manual — sklearn does this for you)
rng = np.random.default_rng(42)

X = np.arange(100).reshape(20, 5)  # 20 samples, 5 features
y = np.random.randint(0, 2, 20)    # binary labels

# Shuffle indices, then split
indices = rng.permutation(len(X))
split = int(0.8 * len(X))
train_idx, test_idx = indices[:split], indices[split:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print(f"Train: {X_train.shape}, Test: {X_test.shape}")

Train: (16, 5), Test: (4, 5)


In [35]:
# Pattern 7: Cosine similarity — used in NLP, recommendation systems
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

vec1 = np.array([1, 2, 3])
vec2 = np.array([1, 2, 3.1])
vec3 = np.array([-1, -2, -3])

print(f"Similar vectors:  {cosine_similarity(vec1, vec2):.4f}")   # ≈ 1.0
print(f"Opposite vectors: {cosine_similarity(vec1, vec3):.4f}")   # ≈ -1.0

Similar vectors:  0.9999
Opposite vectors: -1.0000


In [36]:
# Pattern 8: Confusion matrix (manual) and accuracy
y_true = np.array([0, 1, 1, 0, 1, 0, 1, 1])
y_pred = np.array([0, 1, 0, 0, 1, 1, 1, 1])

accuracy = np.mean(y_true == y_pred)  # Boolean mean = proportion of True
print(f"Accuracy: {accuracy:.2%}")

# Breakdown
tp = np.sum((y_true == 1) & (y_pred == 1))  # true positives
fp = np.sum((y_true == 0) & (y_pred == 1))  # false positives
fn = np.sum((y_true == 1) & (y_pred == 0))  # false negatives
tn = np.sum((y_true == 0) & (y_pred == 0))  # true negatives
print(f"TP={tp}, FP={fp}, FN={fn}, TN={tn}")

precision = tp / (tp + fp)
recall = tp / (tp + fn)
print(f"Precision: {precision:.2f}, Recall: {recall:.2f}")

Accuracy: 75.00%
TP=4, FP=1, FN=1, TN=2
Precision: 0.80, Recall: 0.80


In [37]:
# Pattern 9: Pandas ↔ NumPy interop
# This is how the two libraries connect
import pandas as pd

# DataFrame to NumPy
df = pd.DataFrame({'feature1': [1, 2, 3], 'feature2': [4, 5, 6]})
arr = df.values         # or df.to_numpy() (preferred)
print("df.to_numpy():\n", df.to_numpy())
print("Type:", type(arr))
print("Shape:", arr.shape)

# NumPy to DataFrame
arr = np.array([[10, 20], [30, 40], [50, 60]])
df_new = pd.DataFrame(arr, columns=['A', 'B'])
print("\nNumPy → DataFrame:\n", df_new)

# Single column to NumPy
series_arr = df['feature1'].to_numpy()
print("\nSeries → array:", series_arr)

df.to_numpy():
 [[1 4]
 [2 5]
 [3 6]]
Type: <class 'numpy.ndarray'>
Shape: (3, 2)

NumPy → DataFrame:
     A   B
0  10  20
1  30  40
2  50  60

Series → array: [1 2 3]


## Quick Reference: NumPy → Pandas Translation

| NumPy | Pandas Equivalent | Notes |
|---|---|---|
| `a[a > 5]` | `df[df['col'] > 5]` | Boolean indexing |
| `a[mask1 & mask2]` | `df[(cond1) & (cond2)]` | Combined filters |
| `np.where(cond, a, b)` | `np.where(cond, a, b)` | Same function! |
| `a.mean()` | `df['col'].mean()` | Same method name |
| `a.mean(axis=0)` | `df.mean()` | Column means |
| `a.mean(axis=1)` | `df.mean(axis=1)` | Row means |
| `a.reshape(-1, 1)` | `df[['col']]` | 2D column |
| `np.isnan(a)` | `df.isna()` / `df.isnull()` | Missing values |
| `a.astype('float32')` | `df['col'].astype('float32')` | Type conversion |
| `np.unique(a)` | `df['col'].unique()` | Unique values |
| `np.argsort(a)` | `df.sort_values()` | Sorting |
| `np.concatenate` | `pd.concat` | Stacking |
| `a.T` | `df.T` | Transpose |
| `df.values` / `df.to_numpy()` | — | Pandas → NumPy |